CFLAGS=
LIBFLAG=
LUA_LIB=
LUA_INCDIR=
LUA_LIBDIR=
INST_PREFIX=

all:
        cmake --debug-output -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="$(CFLAGS)" -DCMAKE_EXE_LINKER_FLAGS_RELEASE="$(LIBFLAG)" -DKAME_LUA_INCDIR=$(LUA_INCDIR) -DKAME_LUALIB=$(LUA_LIBDIR)\$(LUALIB) -DKAME_BINDING_LUA=ON -DCMAKE_INSTALL_PREFIX=$(INST_PREFIX)

install:
        cmake --build build --config Release --target install --parallel --verbose
